/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;

public interface RNCProgressBarManagerInterface<T extends View> {
  void setStyleAttr(T view, @Nullable String value);
  void setIndeterminate(T view, boolean value);
  void setProgress(T view, double value);
  void setAnimating(T view, boolean value);
  void setColor(T view, @Nullable Integer value);
}
