/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaDelegate.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;
import com.facebook.react.bridge.ColorPropConverter;
import com.facebook.react.uimanager.BaseViewManagerDelegate;
import com.facebook.react.uimanager.BaseViewManagerInterface;

public class RNCProgressBarManagerDelegate<T extends View, U extends BaseViewManagerInterface<T> & RNCProgressBarManagerInterface<T>> extends BaseViewManagerDelegate<T, U> {
  public RNCProgressBarManagerDelegate(U viewManager) {
    super(viewManager);
  }
  @Override
  public void setProperty(T view, String propName, @Nullable Object value) {
    switch (propName) {
      case "styleAttr":
        mViewManager.setStyleAttr(view, value == null ? null : (String) value);
        break;
      case "indeterminate":
        mViewManager.setIndeterminate(view, value == null ? false : (boolean) value);
        break;
      case "progress":
        mViewManager.setProgress(view, value == null ? 0f : ((Double) value).doubleValue());
        break;
      case "animating":
        mViewManager.setAnimating(view, value == null ? true : (boolean) value);
        break;
      case "color":
        mViewManager.setColor(view, ColorPropConverter.getColor(value, view.getContext()));
        break;
      default:
        super.setProperty(view, propName, value);
    }
  }
}
