
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsH.js
 */
#pragma once

#include <jsi/jsi.h>
#include <react/renderer/components/view/ViewProps.h>
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/graphics/Color.h>

namespace facebook {
namespace react {

class JSI_EXPORT RNCProgressBarProps final : public ViewProps {
 public:
  RNCProgressBarProps() = default;
  RNCProgressBarProps(const PropsParserContext& context, const RNCProgressBarProps &sourceProps, const RawProps &rawProps);

#pragma mark - Props

  std::string styleAttr{};
  bool indeterminate{false};
  float progress{0.0};
  bool animating{true};
  SharedColor color{};
};

} // namespace react
} // namespace facebook
